name: Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt:
    name: Code Format
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0
      - name: format
        run: terraform fmt -check -diff
      - name: init
        run: terraform init -upgrade
      - name: validate
        run: terraform validate -no-color
